version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - .:/var/www/html/wp-content/plugins/DockerfileBrush

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: example
